name: n versioning

on:
  push:
    branches:
      - main

jobs:
  create-version-tag:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # libpng15のキャッシュをチェック
      - name: Cache libpng15
        id: cache-libpng15
        uses: actions/cache@v3
        with:
          path: ~/libpng15-install
          key: libpng15-1.5.30-${{ runner.os }}
          restore-keys: |
            libpng15-1.5.30-

      # 最新のnで始まるタグを取得(無い場合はn0とする)
      - name: Get latest version tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag --list 'n*' --sort=-v:refname | head -n 1)
          if [ -z "$latest_tag" ]; then
            echo "latest_tag=n0" >> $GITHUB_ENV
          else
            echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          fi

      # 新しいバージョンを計算
      - name: Calculate new version
        id: calculate_version
        run: |
          latest_number=${{ env.latest_tag#n }}
          new_number=$((latest_number + 1))
          echo "new_tag=n$new_number" >> $GITHUB_ENV

      # 新しいタグを作成してプッシュ
      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
